### ISSUE TITLE
IOS push notifications are not working

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14704]
# Bug Report

## Problem 
currently on IOS notifications are not working - tried in 1-1, community, group chats

#### Expected behavior
can see PN

#### Actual behavior
no PN

### Reproduction

1) Open Status
2) Android: Add contact, start 1-1 chat
3) IOS: turn on PNs in Advanced > Notifications
4) IOS: put app in the background
5) Android: send message to IOS device

### Additional Information

- Status version: nightly 04/01/23
- Operating System: iOS 16.1.1

[comment]: # (Please, add logs/notes if necessary)

[logs (23).zip](https://github.com/status-im/status-mobile/files/10343234/logs.23.zip)

**Comment by cammellos** [comment]
This is due to push notification servers running only on waku-1.

We should run them as well on waku-2, @jakubgs should be able to help you set that up.
Just make sure you are not running them as a mailserver/waku-1  service, since that's no needed.
This would be a good task for someone who wants to have an insight on how the infrastructure works.

It should be mostly a change of config + deployment, if everything goes smoothly.

**Comment by jakubgs** [comment]
Oh, I think i know what this is caused by:
```yaml
# iOS API access key in one of 3 formats: pem, p12 or p8
gorush_ios_key_contents: '<contents of the p8 key file>'
# KeyID from developer account (Certificates, Identifiers & Profiles -> Keys)
gorush_ios_key_id: '<ios_key_id>'
# TeamID from developer account (View Account -> Membership)
gorush_ios_team_id: '<ios_team_id>'
```
https://github.com/status-im/infra-misc/blob/master/ansible/roles/gorush/README.md

I think the change in the Apple Org ownership of the app has caused this.
